package COMMONGOAL;

public enum CommonID {
    SIXGROUPSTWOTILES,
    FOURGROUPSFOURTILES,
    FOURCORNERS,
    SAMETYPESQUARE,
    THREECOLUMNSSIXTILES,
    EIGHTTILESSAMETYPE,
    FIVETILESDIAGONAL,
    FOURLINESFIVETILES,
    TWOCOLUMNSSIXTILES,
    TWOLINESFIVETILES,
    FIVETILESX,
    DECREASETILES,
}


